# Site settings
title: My Jekyll Demo Site
email: amandavisconti@gmail.com
description: > 
  My site for demonstrating how to build a Jekyll website hosted on GitHub Pages, built for a Programming Historian lesson.
# baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: macintosh_i7
github_username:  imacj

# Build settings
markdown: kramdown
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
